### ISSUE TITLE
no offline mode

### ISSUE THREAD

**Issue by zezadas** [SpockBotMC/SpockBot#35]
https://github.com/SpockBotMC/SpockBot/commit/47919485da01f55565932b6e985f380a3a2d4a88

I think this commit breaks offline demo

**Comment by nickelpro** [comment]
`{'auth': {'authenticated': False}}`

**Comment by zezadas** [comment]
I did that, and is not working
I have 
start_settings = {
    'username': 'player_name',
    'authenticated': False,
}

the only way I got to run the demo was changing 

default_settings = {
	'authenticated': True,  <-- This True to False
	'sess_quit': True,
}
in file spock/plugins/core/auth.py

**Comment by nickelpro** [comment]
Settings parser doesn't work like that, I haven't documented it (yet?)

By passing a dict to the "start" parameter, you're telling **ONLY** the "stayrt" plugin that those are the settings you want it to use. Start plugin doesn't care about authentication, you can either pass `{'authenticated': False}` as an "auth" parameter or you can build a more general settings dict and pass that to the "settings" parameter.

Anyway, fixed in https://github.com/SpockBotMC/SpockBot-Contrib/commit/8f39df86795b19bc2f36ce79c9e62e321c8ea4cf

**Comment by zezadas** [comment]
humm ok.
Now, I understand, thanks
